Output ../../screenshots/multichoose.gif

Set FontFamily "CaskaydiaCove Nerd Font"
Set FontSize 22
Set Width 600
Set Height 300
Set Padding 20
Set TypingSpeed 50ms

Type 'go run main.go' Enter
Sleep 1s

Space@400ms Space@400ms Down@400ms Space@400ms Down@400ms Space@400ms
Enter

Sleep 400ms

Space@400ms Space@400ms Down@400ms  Type@400ms '??' Space@400ms Down@400ms Space@400ms
Enter

Sleep 2s

# vim:filetype=conf
